language: node_js

node_js:
  - "node"
  - "8"

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

services: mongodb

script:
  - npm start &
  - npm test
